---
  hosts:
    type: "string"
    description: "ssh hosts"
    required: true
  username:
    type: "string"
    description: "ssh user"
    required: true
  ssh_key:
    type: "string"
    description: "ssh key and not path"
    required: true

